name: repos-uploader
version: 0.0.0.0
synopsis: |
  Download metadata for a list of GitHub repos and save it to Airsequel
description: |
  For more information check out the readme.
homepage: https://github.com/Airsequel/repos-uploader#readme
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: adrian@feram.io
copyright: Adrian Sieber
category: Web

extra-source-files:
  - readme.md

dependencies:
  - aeson
  - base
  - protolude
  - raw-strings-qq
  - text
  - http-link-header
  - http-types
  - network-uri
  - time

default-extensions:
  - ImportQualifiedPost
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  language: GHC2021
  source-dirs: source
  dependencies:
    - http-client-tls
    - http-client
    - github

executables:
  repos-uploader:
    language: GHC2021
    source-dirs: app
    main: Main.hs
    dependencies:
      - http-client-tls
      - http-client
      - github
