name: airput
version: 0.0.0.0
synopsis: CLI tool for populating Airsequel with data.
description: For more information check out the readme.
homepage: https://github.com/Airsequel/Airput#readme
license: AGPL-3.0-or-later
author: Adrian Sieber
maintainer: adrian@feram.io
copyright: Adrian Sieber
category: Web

extra-source-files:
  - readme.md

dependencies:
  - aeson
  - aeson-pretty
  - base
  - bytestring
  - directory
  - filepath
  - http-client
  - http-client-tls
  - http-link-header
  - http-types
  - network-uri
  - optparse-applicative
  - protolude
  - raw-strings-qq
  - text
  - time
  - vector

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedStrings
  - RecordWildCards

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  language: GHC2021
  source-dirs: source

executables:
  airput:
    language: GHC2021
    source-dirs: app
    main: Main.hs
